FROM node:22.13-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci --omit=dev && npx prisma generate

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["node", "dist/server.js"]
